import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <header className="bg-gray-100 dark:bg-gray-800 p-4 shadow">
          <h1 className="text-xl font-bold">Gallery Hub</h1>
        </header>
        <main className="flex-1 p-4">{children}</main>
        <footer className="bg-gray-100 dark:bg-gray-800 p-4 text-center">
          © 2025 Gallery Hub. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
